apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-depolyment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: hb_mysql:v4
        env:
        - name: TZ
          value: "Asia/Shanghai"
        args:
        - mysqld
        - --character-set-server=utf8
        ports:
          - containerPort: 3306
        readinessProbe:
          tcpSocket:
            port: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: timezone
          mountPath: /etc/localtime
      volumes:
      - name: data
        hostPath:
          path: /data/application/data/mysql
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
#      nodeSelector:
#        disktype: ssd

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - protocol: TCP
    nodePort: 30002
    port: 3306 
    targetPort: 3306

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-depolyment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: hb_redis:v4
        env:
        - name: TZ
          value: "Asia/Shanghai"
        ports:
          - containerPort: 6379 
        readinessProbe:
          tcpSocket:
            port: 6379
#      nodeSelector:
#        disktype: ssd

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - protocol: TCP
    nodePort: 30004
    port: 6379 
    targetPort: 6379

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tomcat-depolyment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: hb_tomcat:v4
        env:
        - name: TZ
          value: "Asia/Shanghai"
        ports:
          - containerPort: 8080 
        readinessProbe:
          httpGet:
            scheme: HTTP
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /usr/local/tomcat/webapps/hanshang-coreService
      volumes:
      - name: data
        hostPath:
          path: /data/application/hb-tomcat/hanshang-coreService
      initContainers:
      - name: init-busy
        image: busybox
        command: ['sh','-c','until nslookup mysql-svc; do echo waiting for mysql; sleep 2; done;']
        command: ['sh','-c','until nslookup redis-svc; do echo waiting for mysql; sleep 2; done;']
      restartPolicy: Always
#      nodeSelector:
#        disktype: ssd

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  type: NodePort
  selector:
    app: tomcat
  ports:
  - protocol: TCP
    nodePort: 30003
    port: 8080 
    targetPort: 8080 

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-depolyment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: hb_nginx:v4
        env:
        - name: TZ
          value: "Asia/Shanghai"
        ports:
          - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html/
        - name: configure
          mountPath: /etc/nginx/nginx.conf
        readinessProbe:
#          exec:
#            command:
#            - cat
#            - /usr/share/nginx/html/index.html
          httpGet:
            scheme: HTTP
#            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      initContainers:
      - name: init-busy
        image: busybox 
        command: ['sh','-c','until nslookup mysql; do echo waiting for mysql; sleep 2; done;']
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          path: /data/application/hb-nginx/dist 
      - name: configure
        hostPath:
          path: /data/application/hb-nginx/nginx.conf
#      nodeSelector:
#        disktype: ssd

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort 
  selector:
    app: nginx 
  ports:
  - protocol: TCP
    nodePort: 30001
    port: 80 
    targetPort: 80
