apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka-depolyment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        imagePullPolicy: IfNotPresent
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-svc"
        - name: KAFKA_CREATE_TOPICS
          value: "aqi_test:1:3,CE_TEST_1:1:3,DeviceData:1:3,DeviceInfo:1:3,PointData:1:3,PointInfeso:1:3,PointInfo:1:3,StationData:1:3"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-svc:2181
        - name: KAFKA_BROKER_ID
          value: "0"
##        - name: KAFKA_LOG4J_LOGGERS
##          value: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
#        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
#          value: 1
        - name: KAFKA_LOG_DIRS
          value: /data/kafka/data
#        - name: KAFKA_DELETE_TOPIC_ENABLE
#          value: "true"
#        args:
#        - /opt/kafka/bin/kafka-server-start.sh 
#        - /data/kafka/conf/server.properties 
#         - /bin/sh
#         - -c
#         - sleep 100000
        ports:
          - containerPort: 9092
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 10
          periodSeconds: 5 
        volumeMounts:
        - name: data
          mountPath: /data/kafka
        - name: timezone
          mountPath: /etc/localtime
#        - name: configure
#          mountPath: /conf
      volumes:
      - name: data
        hostPath:
          path: /data/kafka
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
#      - name: configure 
#        hostPath:
#          path: /data/kafka/conf 
      initContainers:
      - name: init-busy
        image: busybox
        command: ['/bin/sh','-c','until nslookup zookeeper-svc; do echo waiting for mysql; sleep 2; done;']
      restartPolicy: Always
      nodeSelector:
        disktype: ssd

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
  - protocol: TCP
    nodePort: 30009
    port: 9092
    targetPort: 9092 
