apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-depolyment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: hb_nginx:v4
        env:
        - name: TZ
          value: "Asia/Shanghai"
        ports:
          - containerPort: 80
        volumeMounts:
        - name: data
          mountPath: /usr/share/nginx/html/
        - name: configure
          mountPath: /etc/nginx/nginx.conf
        readinessProbe:
#          exec:
#            command:
#            - cat
#            - /usr/share/nginx/html/index.html
          httpGet:
            scheme: HTTP
#            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
      initContainers:
      - name: init-cirros
        image: busybox 
        command: ['sh','-c','until nslookup mysql; do echo waiting for mysql; sleep 2; done;']
      restartPolicy: Always
      volumes:
      - name: data
        hostPath:
          path: /data/application/hb-nginx/dist 
      - name: configure
        hostPath:
          path: /data/application/hb-nginx/nginx.conf
#      nodeSelector:
#        disktype: ssd

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort 
  selector:
    app: nginx 
  ports:
  - protocol: TCP
    nodePort: 30001
    port: 80 
    targetPort: 80
