apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-depolyment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: hb_redis:v4
        env:
        - name: TZ
          value: "Asia/Shanghai"
        ports:
          - containerPort: 6379 
        readinessProbe:
          tcpSocket:
            port: 6379
#      nodeSelector:
#        disktype: ssd

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  type: NodePort
  selector:
    app: redis
  ports:
  - protocol: TCP
    nodePort: 30004
    port: 6379 
    targetPort: 6379
