apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper-depolyment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: zookeeper 
        env:
        - name: TZ
          value: "Asia/Shanghai"
        ports:
          - containerPort: 2181
        readinessProbe:
          tcpSocket:
            port: 2181
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /data
        - name: timezone
          mountPath: /etc/localtime
        - name: configure
          mountPath: /conf
      volumes:
      - name: data
        hostPath:
          path: /data/zk/data
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: configure 
        hostPath:
          path: /data/zk/conf 
#      nodeSelector:
#        disktype: ssd

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
spec:
  type: NodePort
  selector:
    app: zookeeper
  ports:
  - protocol: TCP
    nodePort: 30005
    port: 2181
    targetPort: 2181 
