apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: liveness
spec:
  restartPolicy: OnFailure
  containers:
  - name: liveness
    image: centos
    args:
    - /bin/bash
    - -c
    - touch /tmp/a.txt;sleep 30;rm -f /tmp/a.txt;sleep 600
    livenessProbe:
      exec:
        command:
        - cat
        - /tmp/a.txt
      initialDelaySeconds: 10
      periodSeconds: 5
