apiVersion: batch/v1 
kind: Job
metadata:
  name: myjob
spec:
  template:
    metadata:
      name: myjob
    spec:
      containers:
      - name: hello
        image: centos
        command: ['echo','hello world']
      restartPolicy: OnFailure
