apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness
spec:
  restartPolicy: OnFailure
  containers:
  - name: readiness
    image: centos
    args:
    - /bin/bash
    - -c
    - touch /tmp/a.txt;sleep 30;rm -f /tmp/a.txt;sleep 60000
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/a.txt
      initialDelaySeconds: 10
      periodSeconds: 5
