apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: app
    spec:
      containers:
        - name: httpd
          image: httpd
          ports:
          - containerPort: 80
          readinessProbe:
            httpGet:
              scheme: HTTP
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
 name: web-svc
spec:
  type: NodePort
  selector:
    run: app
  ports:
  - protocol: TCP
    nodePort: 30000
    port: 8080
    targetPort: 80
